### ISSUE TITLE
A tr with td/th element in a tfoot tag gets a non-working expansion button

### ISSUE THREAD

**Issue by rouilj** [inlogicstudio/podtable#10]
Hello.

Thanks for your help so far.

This html:
```
 ...
</tbody>
   <tfoot>
   <tr data-ptr-ignore="">
     <td colspan="8">
       <div class="batch-footer">
         1..3 out of 3
       </div>
     </td>
   </tr>
   </tfoot>
```
results in an expansion arrow in the tr. I can upload a full example in a table with
grouping and other headers if you need it.

The `data-ptr-ignore=""` works fine to make podtable skip the expansion control if the tr is in
the tbody. Howvever it doesn't work for a (second) tr in a thead or the tr in a tfoot.
Using either a td or a th inside the tr makes no difference.

Re-reading the docs, it appears to work as documents. `data-ptr-ignore` is only supposed to work on tr tags within in tbody. However I can see uses for it in thead (complex header configurations) as well as tfoot (summary stats, table pagination etc).

Thanks.

**Comment by inlogicstudio** [comment]
Can you please give examples of the complex header configuration likewise the footer as well in HTML

**Comment by inlogicstudio** [comment]
Also are you implying that the footer doesn't have a control column for the footer as it is in the head

**Comment by inlogicstudio** [comment]
Your usage of  podtable is really higher than what i thought alright its a good thing

1. The lib was specifically built with the thought of one row in the header
2. from the link you are more concern about not having a control in your footer i will look into this but it might not be soon

**Comment by rouilj** [comment]
Hi Afuwape:

Have you done any more work on this?

-- rouilj

**Comment by inlogicstudio** [comment]
@rouilj thanks for checking closing the issue made me skipped this but this will be added in the next release hopefully in few days

**Comment by inlogicstudio** [comment]
Alright thanks alot is your experimental repo public

**Comment by rouilj** [comment]
Did you download the test case from: https://www.cs.umb.edu/~rouilj/podtable/podtable.test.html?

**Comment by inlogicstudio** [comment]
The page is not responsive no way I could check the table behavior

**Comment by rouilj** [comment]
The page works fine for me. Did you download it to a directory that includes podtable.css and podtable.js and then open the file in the browser?

Once you do that shrink the window and you will see the portable controls as in:

<img width="423" alt="podtable_with_controls" src="https://user-images.githubusercontent.com/3751752/195132063-61c6db9a-3626-4ff0-855b-ad45215d8804.png">

Note that none of the toggles work which is why the issue was opened.

The 2 header rows that span the table (or span multiple columns) I think break podtable's ability to remove/format columns and causes it to delete rows as described. Note that these two header rows  include the data-ptr-ignore="" attribute.

The grouping headers in the tbody do not have toggles as expected since they have the data-ptr-ignore="" attribute.

In addition there is a toggle in the footer that is not expected since it has the data-ptr-ignore="" attribute.

**Comment by inlogicstudio** [comment]
Please leave the link active

**Comment by inlogicstudio** [comment]
The `data-ptr-ignore` attribute is not meant for the head tag neither the footer  its meant for the body 
for the toggle in the footer i will provide a fix for that but am very sorry multiple header rows is going to break the table and which i cant provide a fix for at the moment and this is because you are the only one with such request at the moment nevertheless if i get more of such use case i will add it

**Comment by inlogicstudio** [comment]
your table example didn't break because of the col span its because the lib is built for  one row in the header

**Comment by inlogicstudio** [comment]
> In addition there is a toggle in the footer that is not expected since it has the data-ptr-ignore="" attribute.

the idea of ignore is to totally ignore the row for control and any of form responsive action

**Comment by inlogicstudio** [comment]
fix has been made for the footer hopefully when i get more request i will allow more rows in header thanks
am closing this issue please if you have any more request hope another issue
