### ISSUE TITLE
Allow element to be passed on init

### ISSUE THREAD

**Issue by andreas-hub** [inlogicstudio/podtable#5]
When you initialize a new potable the first argument is the table selector
```JavaScript
new Podtable('#table', options);
```

I would like to suggest adding the ability to also be able to pass the table element itself. This will make life a lot easier for people using frameworks as they usually have their own way to get an element and also have weird scopes making it harder for this lib to work as is.

```JavaScript
const tableElement = document.querySelector('#table');
new Podtable(tableElement, options);
```

**Comment by inlogicstudio** [comment]
This is a very good suggestion and it will be included in the lib todo if you having issues using it with a framework do reply.

**Comment by inlogicstudio** [comment]
@andreas-hub  check the dev branch on the latest commits the feature you mentioned above will come with the next podtable version

**Comment by andreas-hub** [comment]
That was very fast, I'm realy grateful, thank you.
