### ISSUE TITLE
Throwing "Cannot read properties of undefined (reading 'classlist')"

### ISSUE THREAD

**Issue by rouilj** [inlogicstudio/podtable#6]
Hello. I like how your library handles table resizes. I ma trying to make i work with my
app.

To start with I am using a simple display table inside a form with a checkbox for each row.
The files podtable.js and podtable.css were downloaded from from github at revision 
8b62d73. Browser is Google Chrome:  96.0.4664.45 on windows 10.

I have applied podtable to my existing table using:

```
    Podtable(document.querySelector("table.list"),
                                    { "keepCell": [1,3],
                                      "priority": [2,7,6,5]});

```
The final th/td in each table row has a main-toggle/toggle class applied. Hovering over the toggle column shows a hand cursor.

When I shrink the table, the last (toggle) column is removed from the table. Also I never see a dropdown arrow indicator in that toggle column. Adding the last column to keepCell has no effect.

As I resize, it throws a ton of:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
    at y (podtable.js:1)
    at w (podtable.js:1)
    at ResizeObserver.<anonymous> (podtable.js:1)
```
errors.

When I look at the example on codepen, I see empty class="" for the rows
to be removed that are not in the original html. On my example table I have no class attributes on any of my th/td elements. If I manually add class="" to the html the errors
go away for my first resize. This resize removes the toggle column and the columns at the far right side of the table which is not correct. Column #2 is not removed as requested. After that resizes (larger or smaller) again result in the errors above.

Any ideas on what is happening here and how to fix it? Also is there an version of the code available that I can use with the debugger? I have the map file in the same path as the js
file and can format the code, but variables like e, n and t don't tell me much.

Thanks.

-- rouilj

**Comment by rouilj** [comment]
Ok, I think I have an idea what's happening here.

Using the map, the traceback is:
```
podtable.js:formatted:138 Uncaught TypeError: Cannot read properties of undefined (reading 'classList')
    at y (podtable.js:formatted:138)
    at E (podtable.js:formatted:165)
    at podtable.js:formatted:197
    at podtable.js:formatted:265
    at HTMLDocument.<anonymous> (FormChanged.js:413)
```

line 138 is:
``` 
  i.classList.contains("child") || i.cells[e].classList.add("hidden")
```

The last row in my table is a navigation row with a td that spans all 10 remaining columns. As a result `i.cells` has only one element and `e` has a value of 2. Hence boom.

Maybe change this to:
```
    i.classList.contains("child") || (i.cells.length > e && i.cells[e].classList.add("hidden"))
            } 
```
or store the number of cells in the header and only apply this to rows that have the same number of cells.

Other versions of the table allow grouping of rows by one or more properties. Each group header spans all rows in the table and will have the same issue. So supporting a use case including td/th that span the entire table is useful. In my case, group headers and pagination footer starts in column 0 so would never be hidden.

I removed pagination footer generation from the table. When I do this the dropdown markers show up but they are at the end of the cell before the last cell in the body of the table and well out of the header row  for the header control. This is fixed by removing position absolute from this rule:
```
#podtable-container table.show-toggle .toggle::before,
#podtable-container table.show-toggle .main-toggle::before {
...
    position: absolute !important;
```
This change places the marker in the center of the cell. Then setting 'margin-top' for the ::before element to 0.5rem puts it slightly below the top of the cell in both the header and body rows.

Changing the background to white results in the following:

<img width="484" alt="image" src="https://user-images.githubusercontent.com/3751752/143670719-95bcc688-2567-4946-a35f-5477f84bb5b6.png">

which is reasonable.

**Comment by inlogicstudio** [comment]
- first install the lib from npm 
In the podtable instance the first param is either a table element or a table selector that is an actual table but am seeing `table.list`

**Comment by inlogicstudio** [comment]
Can i see the actual code implementation that's how  i will be able to detect what's wrong paste the HTML and the podtable instance

**Comment by inlogicstudio** [comment]
From the image above I can see you are trying to implement a row group is that right ?

**Comment by rouilj** [comment]
> * first install the lib from npm

What purpose does this serve? I am just loading the files from the web server into a web page.
No node/npm needed.

> In the podtable instance the first param is either a table element or a table selector
> that is an actual table but am seeing `table.list`

I am passing:
```
document.querySelector("table.list")
```
isn't that the table element itself?

> Also you are not meant to add the index of the control cell in the keep cell array
> as it will not be hidden by default

I understand that but the control cell column was being hidden so I tried it in case that gave you additional info to figure out what was happening.

**Comment by rouilj** [comment]
> Can i see the actual code implementation that's how i will be able to detect what's wrong
> show the HTML and the podtable instance

I am guessing this comment was put in before my followup. With my followup
it should be easy for you to create a simple html table with a row
spanning all columns and see the problem.

The podtable command is as given in the original post

**Comment by rouilj** [comment]
> From the image above I can see you are trying to implement a row group is that right ?

The image shows a working podtable instance. To make it work I had to removed any rows that spanned all the columns in the table.

I am not sure what you mean by "row group". The only reference I find to html table and row group is using one or more tbody tags inside a table. (Note I am not doing this. Also podtable's healthcheck function explicitly prevents more than one tbody.) 

When I have group headers, I have:
```
table
   thead
      tr
        th ... /th (repeat for each column)
     tr
   /thead
  tbody
      tr  (first row with group header)
        th colspan=11    group value
        /th
      /tr
      tr (data row)
         td ... /td  (repeat for each column)
      /tr
     (more tr.../tr pairs)
     tr  th colspan="11" (another grouping header) /tr /th
      tr (more data rows)
         td ... /td  (repeat for each column)
      /tr
     (more tr.../tr pairs)
   ....
   tr
      td colspan="11" /td  (pagination controls)
   /tr
  /tbody
/table
```
Here is a screenshot of a table showing group headers plus page navigation:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/3751752/143688364-b0daaa6a-1fe3-4f29-a278-4a1bfd13058e.png">

With the rows spanning the table podtable throws the error I reported as it processes
each of the spanning rows.

**Comment by inlogicstudio** [comment]
Alright now i get what you are trying to achieve, so now to  solve your issue podtable needs to be able ignore some rows.
i will add that to the todo list in the coming week i will roll out a version for it also

> Other versions of the table allow grouping of rows by one or more properties.

does that mean previous version of podtable doesn't throw error when you try to do this

**Comment by rouilj** [comment]
> Alright now i get what you are trying to achieve, so now to solve your issue podtable needs to be
> able ignore some rows.

In general yes. However handling the exception by ignoring it and not trying to change that row
would work as well. Currently any row that has cells that use colspan will fail because the number of
cells in the row will be less than the number you have in say a header that doesn't have cells
that use colspan.

> i will add that to the todo list in the coming week i will roll out a version
> for it also

Thanks. I also have a request for hiding the control column until you actually put a control in it, but that can go in another ticket.

> > Other versions of the table allow grouping of rows by one or more properties.
> 
> does that mean previous version of podtable doesn't throw error when you try to do this

They all throw an error when processing a row with fewer cells than podtable expects.
