### ISSUE TITLE
Hide control column until it is used.

### ISSUE THREAD

**Issue by rouilj** [inlogicstudio/podtable#7]
The preferred way to use podtable is to add an emtpy cell at the end of every row to hold the
control element.

This leaves extra blank space or a bordered cell at then end that looks weird.

<img width="521" alt="image" src="https://user-images.githubusercontent.com/3751752/143721047-ca4fc620-f38d-4e3d-8c7d-dc2bce342a43.png">

I can add a class to the control cell to set "display: none". Podtable will properly fill it with a control when the table is resized. However since the cell is hidden the control isn't shown.

As an enhancement, remove a user specified class when the control is added/displayed. When the display control is removed, add the class back to the control cells in each row.

Maybe add an option:
```
hide_class: "nodisplay"
```
to Podtable. This class would be added/removed to hide/unhide the control column. Default value is empty.
If not set no classes are added/removed.

**Comment by inlogicstudio** [comment]
Its not mandatory for you to define an empty cell for the control toggle, podtable will always use the last cell of every row as the control toggle

hiding the control column until its is used will render the calculation for the maximum squish of the table in accurate to iterate its not compulsory to define an empty cell for the control toggle

**Comment by inlogicstudio** [comment]
when you look at jq datatable responsive plugin the control column is always defined on cells with data either the last cell or the first cell of the row

so what i suggest you do here is not to use an empty cell for the control and increase the padding for the last cell so as to accommodate the control toggle

the idea of using an empty cell for the control column is to have  flexibility over you table data

**Comment by rouilj** [comment]
In my use case this is difficult as I never know what the last column will be. The table is the result of a search and  the user can choose how many and which columns to display. So adding an extra column handles this efficiently.

I suppose I can use tr:nth-last-child(1)  or tr td:last-of-type (tr th:last-of-type) to target the last cell in each row. rather than writing javascript for it. How much padding is required to accommodate the control? The control looks like it's a square at 1.075 rem? Is this correct? So padding of 1.5rem should be sufficient right?

It will still look strange to have the padding if there is no control.

Hmm, is the show-toggle class added to the table only when the control is shown? If so maybe I can use table.show-toggle as a switch. Not sure what that will do with cells that span all rows though.

**Comment by rouilj** [comment]
When I add padding to the cell, it doesn't increase the size of the cell. The text inside it is wrapped/scrunched to account for the padding. This makes reading the data in the cell difficult.

E.G.

<img width="171" alt="image" src="https://user-images.githubusercontent.com/3751752/143776178-3a87863a-e3fa-4b5e-b9ea-b8ab3a23e660.png">

The first non-header cell has padding-inline-end: 1.5rem; applied. The cell under it doesn't. (Note the position of the controls. This is with the default settings in the stylesheet. I made the background of the control element white so it's visible.)

Also podtable changes the cursor on the last cell to the pointer/hand cursor. It should change it just when hovering over the control so it's obvious that the text in the cell can be selected.

That's another reason to use an additional cell. With the control in place it
looks like the entire cell is clickable. Which is nice in that it increases the area of interaction. What happens if there is a link, input or other interactive element in the cell? I am not sure how the control and other clickable element will interact.

**Comment by inlogicstudio** [comment]
If you check the readme issue #6 on row group it has been added to the to do list i will add that of control styling as well

And if I may ask you what do you see about allowing user to define their own element that can be placed anywhere as the control toggle as that gives the whole freedom on the control toggle styling and other stuffs

**Comment by rouilj** [comment]
> what do you see about allowing user to define their own element that

So you mean something like:
```
  <thead>
     <tr>
       <th>
         <span class="main-toggle"></span>
         some other text in the cell
       </th>
     </tr>
  </thead>
```
or
```
    <td>
      <div class="toggle"> </div>
      some data
    </td>
     <td> ... </td>
  </tr>
  <tr>
     ...
  </tr>
```
where you put the control in the elements identified by `.main-toggle` and `.toggle`?

That could work. It would also support adding  a standalone column with:

```
  <tbody>
     <td> ... </td>
     <td class="toggle"></td>
  </tbody>
```

**Comment by rouilj** [comment]
Also for those following along at home, I added a final th/td at the end of each row
in the table. I also added:

```
#podtable-container table td:last-of-type,
#podtable-container table th:last-of-type { display: none; }
#podtable-container table.show-toggle tr td:last-of-type,
#podtable-container table.show-toggle tr th:last-of-type { display: revert; }
```
to hide the trailing cell until it gets used seems to work.

**Comment by inlogicstudio** [comment]
> So you mean something like:

yes and i will add the custom control toggle to the to do list

**Comment by rouilj** [comment]
Yeah that would work I think.
