### ISSUE TITLE
CSS for #podtable-container includes overflow-x which breaks sticky heading.

### ISSUE THREAD

**Issue by rouilj** [inlogicstudio/podtable#9]
Hello again:

My table is set up with header row and group headers. Both sets of headers are set to be sticky
so that they are kept visible as you scroll down the table.

When used with podtable, the sticky headers don't work and scroll off the page.

I traced this down to the CSS style: x-overflow on the #podtable-container. If I remove that
declaration sticky headers work again. I have tested without that CSS item and everything still works
as I expect.

I don't see any bad effects from removing overflow-x. It looks like that was
present in the first commit so I am not sure what problem it addresses or why it is needed.

Thanks.

**Comment by inlogicstudio** [comment]
Alright i will look into it and get back to you

**Comment by inlogicstudio** [comment]
Hi  there the x-overflow wont let the table overflow break your page while podtable is still calculating the rows to hide and this is particularly useful for table rows with many cells, but most cases you will barely notice it especially  if you are in a routing framework vue or react so you can remove it in other to get your sticky header working

**Comment by inlogicstudio** [comment]
i will close this issue now you can comment on it and i will reopen for any further talks and don't forget to hit the star button if you haven't

**Comment by rouilj** [comment]
Interesting. Even with 26 columns, I don't see the layout breaking when I override the
overflow-x setting. Thanks for the info though, if I see the flash of unformatted layout, I'll know why.
